version: "3.1"
services:
  db:
    container_name: buchDB
    image: mariadb:10.5
    ports:
      - "3304:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=buchDB"
    volumes:
      - ./data:/var/lib/mysql
