name: build and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: java installieren
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: run gradle
        run: ./gradlew check